### PR TITLE
fix(android): resolve android icon bug

### LINKED ISSUE #46: Require local image throws error for Android largeIcon
Hey there! 

The library is looking fantastic at the moment but there is one issue that I've run into recently. When using a local image for largeIcon, an error is thrown asking for a string. I've attached incredibly basic code below. This is through the function notifee.displayNotification

```Javascript
android: {
            channelId: 'message',
            timestamp: Date.now(),
            showTimestamp: true,
            largeIcon: require('./Images/logo.png') // This throws the error "notifee.displayNotification(*) 'notification.android.largeIcon' expected a string value."
          },
```

### PR DESCRIPTION
**Pull request by russellwheatley**
fixes #46

### CODE REVIEW

File: src/validators/validateAndroidNotification.ts [hunk 1]
```diff
@@ -280,11 +280,14 @@ export default function validateAndroidNotification(
    * largeIcon
    */
   if (hasOwnProperty(android, 'largeIcon')) {
-    if (!isString(android.largeIcon) || !android.largeIcon) {
-      throw new Error("'notification.android.largeIcon' expected a string value.");
+    if (!isNumber(android.largeIcon) || !android.largeIcon) {
```
Comment (Salakar) [inline src/validators/validateAndroidNotification.ts:283]: This has broken passing string urls in, argument type should be 

```ts
largeIcon?: string | number | object;
``

And if type is number or object it should go through the resolve asset source, otherwise if string (url) then send it direct to `out.largeIcon`


Types update is missing in this PR too

File: src/types/NotificationAndroid.ts [hunk 2]
```diff
@@ -508,22 +510,24 @@ export interface AndroidBigPictureStyle {
   type: AndroidStyle.BIGPICTURE;
 
   /**
-   * A remote http or local file path to the picture to display.
+   * A local file path using the 'require()' method or a remote http to the picture to display.
```
Comment (Salakar) [inline src/types/NotificationAndroid.ts:513]:
```suggestion
   * A local file path using the 'require()' method or a remote HTTP URL to the picture to display.
```

File: src/types/NotificationAndroid.ts [hunk 3]
```diff
@@ -508,22 +510,24 @@ export interface AndroidBigPictureStyle {
...
-  picture: string;
+  picture: string | number | object;
 
   /**
    * If set, overrides the main notification `title` when the notification is expanded.
    */
   title?: string;
 
   /**
+   * A local file path using the 'require()' method or a remote http to the picture to display.
```
Comment (Salakar) [inline src/types/NotificationAndroid.ts:526]:
```suggestion
   * A local file path using the 'require()' method or a remote HTTP URL to the picture to display.
```

File: src/validators/validateAndroidStyle.ts [hunk 4]
```diff
@@ -19,9 +22,12 @@ import { checkForProperty, isArray, isBoolean, isNumber, isObject, isString } fr
 export function validateAndroidBigPictureStyle(
   style: AndroidBigPictureStyle,
 ): AndroidBigPictureStyle {
-  if (!isString(style.picture) || !style.picture) {
+  if (
+    (!isString(style.picture) && !isNumber(style.picture) && !isObject(style.picture)) ||
+    !style.picture
```
Comment (Salakar) [inline src/validators/validateAndroidStyle.ts:27]:
```suggestion
    !style.picture
```

Image assets numbers start from `0` afaik - so I think this validation fail in that scenario, might be best to remove this check from here, and also from the other places that have done it - instead expand the check to check for string length if it's a string. (isObject already handles the undefined scenario)

File: src/validators/validateAndroidStyle.ts [hunk 5]
```diff
@@ -31,14 +37,25 @@ export function validateAndroidBigPictureStyle(
...
+
+    out.picture = image.uri;
+  }
+
   if (checkForProperty(style, 'largeIcon')) {
-    if (!isString(style.largeIcon)) {
+    if (!isString(style.largeIcon) && !isNumber(style.largeIcon) && !isObject(style.largeIcon)) {
       throw new Error(
-        "'notification.android.style' BigPictureStyle: 'largeIcon' expected a string value.",
+        "'notification.android.style' BigPictureStyle: 'largeIcon' expected a number or object created using the 'require()' method or a valid string URL.",
```
Comment (Salakar) [inline src/validators/validateAndroidStyle.ts:49]:
```suggestion
        "'notification.android.style' BigPictureStyle: 'largeIcon' expected a React Native ImageResource value or a valid string URL.",
```

File: src/validators/validateAndroidNotification.ts [hunk 6]
```diff
@@ -280,11 +280,23 @@ export default function validateAndroidNotification(
...
-    if (!isString(android.largeIcon) || !android.largeIcon) {
-      throw new Error("'notification.android.largeIcon' expected a string value.");
+    if (
+      (!isNumber(android.largeIcon) &&
+        !isString(android.largeIcon) &&
+        !isObject(android.largeIcon)) ||
+      !android.largeIcon
+    ) {
+      throw new Error(
+        "'notification.android.largeIcon' expected a number or object created using the 'require()' method or a valid string URL.",
```
Comment (Salakar) [inline src/validators/validateAndroidNotification.ts:290]:
```suggestion
        "'notification.android.largeIcon' expected a React Native ImageResource value or a valid string URL.",
```

File: src/types/NotificationAndroid.ts (hunk 3 above)
Comment (Salakar) [reply src/types/NotificationAndroid.ts:526]: Reason: `http(s)://` & `file://` both supported
